PromptClass: QuestionTableColumnsPrompt
prompt_configs:
  few_shot_text: |
    question: get people name with age equal 25 table: id, name, age
    First need to select all the people from table
    SELECT * FROM table
    Second need to select only people with age equal 25, that corresponds to the column age
    SELECT * FROM table WHERE age = 25
    A: SELECT * FROM table WHERE age = 25
  instruction_text: "Act as a professional SQL developer and answer a question with a step by step reasoning"